import type { MenuItem } from '@shared/domain/menu.types'

export const CONTABILIDAD_FALLBACK_MENUS: MenuItem[] = [
  {
    id: 'cont-fb-dash',
    label: 'Dashboard',
    icon: 'layout-dashboard',
    path: '/contabilidad',
    order: 0,
  },
  {
    id: 'cont-fb-contabilidad',
    label: 'Contabilidad',
    icon: 'book-open',
    path: null,
    order: 1,
    children: [
      {
        id: 'cont-fb-cont-plan',
        label: 'Plan de cuentas',
        icon: null,
        path: '/contabilidad/plan-cuentas',
        order: 0,
      },
      {
        id: 'cont-fb-cont-asientos',
        label: 'Asientos contables',
        icon: null,
        path: '/contabilidad/asientos',
        order: 1,
      },
      {
        id: 'cont-fb-cont-plantillas',
        label: 'Plantillas de asiento',
        icon: null,
        path: '/contabilidad/asientos/plantillas-asiento',
        order: 2,
      },
      {
        id: 'cont-fb-cont-periodos',
        label: 'Periodos contables',
        icon: null,
        path: '/contabilidad/periodos',
        order: 3,
      },
      {
        id: 'cont-fb-cont-cc',
        label: 'Centros de costo',
        icon: null,
        path: '/contabilidad/centros-costo',
        order: 4,
      },
      {
        id: 'cont-fb-cont-cierre',
        label: 'Cierre mensual',
        icon: null,
        path: '/contabilidad/cierre-mensual',
        order: 5,
      },
    ],
  },
  {
    id: 'cont-fb-tesoreria',
    label: 'Tesorería',
    icon: 'landmark',
    path: null,
    order: 2,
    children: [
      {
        id: 'cont-fb-tes-caja',
        label: 'Caja',
        icon: null,
        path: '/contabilidad/tesoreria/caja',
        order: 0,
      },
      {
        id: 'cont-fb-tes-bancos',
        label: 'Bancos',
        icon: null,
        path: '/contabilidad/tesoreria/bancos',
        order: 1,
      },
      {
        id: 'cont-fb-tes-conc',
        label: 'Conciliaciones',
        icon: null,
        path: '/contabilidad/tesoreria/conciliaciones',
        order: 2,
      },
      {
        id: 'cont-fb-tes-mov',
        label: 'Movimientos',
        icon: null,
        path: '/contabilidad/tesoreria/movimientos',
        order: 3,
      },
      {
        id: 'cont-fb-tes-trans',
        label: 'Transferencias',
        icon: null,
        path: '/contabilidad/tesoreria/transferencias',
        order: 4,
      },
    ],
  },
  {
    id: 'cont-fb-comp',
    label: 'Compras',
    icon: 'shopping-cart',
    path: null,
    order: 3,
    children: [
      {
        id: 'cont-fb-comp-fac',
        label: 'Facturas de compra',
        icon: null,
        path: '/contabilidad/compras/facturas',
        order: 0,
      },
      {
        id: 'cont-fb-comp-nc',
        label: 'Notas de crédito',
        icon: null,
        path: '/contabilidad/compras/notas-credito',
        order: 1,
      },
      {
        id: 'cont-fb-comp-nd',
        label: 'Notas de débito',
        icon: null,
        path: '/contabilidad/compras/notas-debito',
        order: 2,
      },
      {
        id: 'cont-fb-comp-prov',
        label: 'Proveedores',
        icon: null,
        path: '/contabilidad/compras/proveedores',
        order: 3,
      },
      {
        id: 'cont-fb-comp-pagos',
        label: 'Pagos',
        icon: null,
        path: '/contabilidad/compras/pagos',
        order: 4,
      },
    ],
  },
  {
    id: 'cont-fb-vent',
    label: 'Ventas',
    icon: 'receipt',
    path: null,
    order: 4,
    children: [
      {
        id: 'cont-fb-vent-fac',
        label: 'Facturas',
        icon: null,
        path: '/contabilidad/ventas/facturas',
        order: 0,
      },
      {
        id: 'cont-fb-vent-bol',
        label: 'Boletas',
        icon: null,
        path: '/contabilidad/ventas/boletas',
        order: 1,
      },
      {
        id: 'cont-fb-vent-nc',
        label: 'Notas de crédito',
        icon: null,
        path: '/contabilidad/ventas/notas-credito',
        order: 2,
      },
      {
        id: 'cont-fb-vent-nd',
        label: 'Notas de débito',
        icon: null,
        path: '/contabilidad/ventas/notas-debito',
        order: 3,
      },
      {
        id: 'cont-fb-vent-cli',
        label: 'Clientes',
        icon: null,
        path: '/contabilidad/ventas/clientes',
        order: 4,
      },
      {
        id: 'cont-fb-vent-cob',
        label: 'Cobros',
        icon: null,
        path: '/contabilidad/ventas/cobros',
        order: 5,
      },
    ],
  },
  {
    id: 'cont-fb-tributos',
    label: 'Tributos',
    icon: 'percent',
    path: null,
    order: 5,
    children: [
      {
        id: 'cont-fb-trib-igv',
        label: 'IGV',
        icon: null,
        path: '/contabilidad/tributos/igv',
        order: 0,
      },
      {
        id: 'cont-fb-trib-det',
        label: 'Detracciones',
        icon: null,
        path: '/contabilidad/tributos/detracciones',
        order: 1,
      },
      {
        id: 'cont-fb-trib-ret',
        label: 'Retenciones',
        icon: null,
        path: '/contabilidad/tributos/retenciones',
        order: 2,
      },
      {
        id: 'cont-fb-trib-per',
        label: 'Percepciones',
        icon: null,
        path: '/contabilidad/tributos/percepciones',
        order: 3,
      },
      {
        id: 'cont-fb-trib-renta',
        label: 'Impuesto a la renta',
        icon: null,
        path: '/contabilidad/tributos/renta',
        order: 4,
      },
    ],
  },
  {
    id: 'cont-fb-libros',
    label: 'Libros electrónicos',
    icon: 'library',
    path: null,
    order: 6,
    children: [
      {
        id: 'cont-fb-lib-rc',
        label: 'Registro de compras',
        icon: null,
        path: '/contabilidad/libros-e/registro-compras',
        order: 0,
      },
      {
        id: 'cont-fb-lib-rv',
        label: 'Registro de ventas',
        icon: null,
        path: '/contabilidad/libros-e/registro-ventas',
        order: 1,
      },
      {
        id: 'cont-fb-lib-diario',
        label: 'Libro diario',
        icon: null,
        path: '/contabilidad/libros-e/libro-diario',
        order: 2,
      },
      {
        id: 'cont-fb-lib-mayor',
        label: 'Libro mayor',
        icon: null,
        path: '/contabilidad/libros-e/libro-mayor',
        order: 3,
      },
      {
        id: 'cont-fb-lib-caja',
        label: 'Libro caja',
        icon: null,
        path: '/contabilidad/libros-e/libro-caja',
        order: 4,
      },
      {
        id: 'cont-fb-lib-bancos',
        label: 'Libro bancos',
        icon: null,
        path: '/contabilidad/libros-e/libro-bancos',
        order: 5,
      },
      {
        id: 'cont-fb-lib-ple',
        label: 'PLE',
        icon: null,
        path: '/contabilidad/libros-e/ple',
        order: 6,
      },
    ],
  },
  {
    id: 'cont-fb-rep',
    label: 'Reportes financieros',
    icon: 'pie-chart',
    path: null,
    order: 7,
    children: [
      {
        id: 'cont-fb-rep-bg',
        label: 'Balance general',
        icon: null,
        path: '/contabilidad/reportes/balance-general',
        order: 0,
      },
      {
        id: 'cont-fb-rep-er',
        label: 'Estado de resultados',
        icon: null,
        path: '/contabilidad/reportes/estado-resultados',
        order: 1,
      },
      {
        id: 'cont-fb-rep-fc',
        label: 'Flujo de caja',
        icon: null,
        path: '/contabilidad/reportes/flujo-caja',
        order: 2,
      },
      {
        id: 'cont-fb-rep-fe',
        label: 'Flujo de efectivo',
        icon: null,
        path: '/contabilidad/reportes/flujo-efectivo',
        order: 3,
      },
      {
        id: 'cont-fb-rep-anal',
        label: 'Análisis financiero',
        icon: null,
        path: '/contabilidad/reportes/analisis-financiero',
        order: 4,
      },
      {
        id: 'cont-fb-rep-kpi',
        label: 'KPIs',
        icon: null,
        path: '/contabilidad/reportes/kpis',
        order: 5,
      },
    ],
  },
  {
    id: 'cont-fb-cfg',
    label: 'Configuración',
    icon: 'settings',
    path: null,
    order: 8,
    children: [
      {
        id: 'cont-fb-cfg-main',
        label: 'Empresa y series',
        icon: null,
        path: '/contabilidad/configuracion',
        order: 0,
      },
      {
        id: 'cont-fb-cfg-tc',
        label: 'Tipos de cambio',
        icon: null,
        path: '/contabilidad/configuracion/tipos-cambio',
        order: 1,
      },
      {
        id: 'cont-fb-cfg-cpe',
        label: 'Trazabilidad CPE',
        icon: null,
        path: '/contabilidad/configuracion/cpe-log',
        order: 2,
      },
    ],
  },
]

export function contabilidadMenusLookComplete(apiMenus: MenuItem[]): boolean {
  if (!apiMenus.length) return false
  const tesoreria = apiMenus.find((m) => m.label.trim() === 'Tesorería')
  const contabilidad = apiMenus.find((m) => m.label.trim() === 'Contabilidad')
  return !!(tesoreria?.children?.length && contabilidad?.children?.length)
}
