export {
  ventasSalesKeys,
  invalidateVentasSalesCache,
  useVentasProcessesList,
  useVentasProcessDetail,
  useVentasCreateProcess,
  useVentasUpdateProcess,
  useVentasUpdateProcessQuiet,
  useVentasPipelineBoard,
  useVentasAddProcessNote,
  useVentasAddActivity,
  useVentasAddReminder,
  useVentasCompleteReminder,
  useVentasSeparationsList,
  useVentasCreateSeparation,
  useVentasClosingsList,
  useVentasCreateClosing,
} from './useVentasSales'
